from django.urls import path
from . import views

urlpatterns = [
    path('api/status/', views.guild_status, name='guild_status'),
    path('api/session/start/', views.start_session, name='start_session'),
    path('api/session/complete/', views.complete_session, name='complete_session'),
    path('api/adventurer/create/', views.create_adventurer,
         name='create_adventurer'),
    path('api/guild/consolidate/', views.consolidate_guild_wealth,
         name='consolidate_wealth'),
    path('api/adventurer/delete/<int:adv_id>/',
         views.delete_adventurer, name='delete_adventurer'),
    path('api/tavern/', views.tavern_recruits, name='tavern_recruits'),
    path('api/habits/', views.list_habits, name='list_habits'),
    path('api/habits/create/', views.create_habit, name='create_habit'),
    path('api/habits/complete/', views.complete_habit, name='complete_habit'),
    path('api/stats/graph/', views.get_stats_data, name='get_stats_data'),
    path('api/inventory/<str:target_type>/<int:target_id>/',
         views.get_inventory, name='get_inventory'),
    path('api/inventory/action/', views.inventory_action, name='inventory_action'),
    path('api/charts/', views.list_charts, name='list_charts'),
    path('api/charts/add_point/', views.add_chart_point, name='add_chart_point'),
    path('api/charts/create/', views.create_chart, name='create_chart'),
    path('api/charts/delete/<int:chart_id>/',
         views.delete_chart, name='delete_chart'),
    path('api/habits/delete/<int:habit_id>/',
         views.delete_habit, name='delete_habit'),
    path('api/habits/undo/<int:habit_id>/',
         views.undo_habit, name='undo_habit'),
    path('api/charts/claim/', views.claim_chart_reward, name='claim_chart_reward'),
    path('api/adventurer/<int:adv_id>/unequip/',
         views.unequip_item, name='unequip_item'),
]
