services:
  # El contenedor de la base de datos
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=supersecret
    ports:
      - "5433:5432"

  # El contenedor aplicación Django / CLI
  web:
    build: .
    # Sincroniza la carpeta actual con el contenedor para no tener que reconstruir 
    # la imagen cada vez que se edite una línea de código en Python.
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_HOST=db  
      - POSTGRES_PORT=5432

# --- Microservicio Node.js ---
  scraper:
    build: ./scraper # Busca el Dockerfile en la carpeta scraper
    env_file:
      - .env # Pasa la clave de TMDB al contenedor
    volumes:
      - ./scraper:/app # Sincroniza los archivos en vivo para desarrollo
      - /app/node_modules # Evita sobreescribir los módulos de Node del contenedor
    depends_on:
      - web # El scraper necesita que Django esté vivo para poder enviarle datos

# volumen persistente para que los datos sobrevivan a reinicios
volumes:
  postgres_data: