services:
  # El contenedor de la base de datos
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=supersecret
    ports:
      - "5434:5432"

  # El contenedor aplicación Django / CLI
  web:
    build: .
    # Sincroniza la carpeta actual con el contenedor para no tener que reconstruir 
    # la imagen cada vez que se edite una línea de código en Python.
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=library_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_HOST=db  
      - POSTGRES_PORT=5432

# --- Microservicios Distribuidos Node.js ---
  scraper-books:
    build: ./scraper
    command: npm run start:books
    volumes:
      - ./scraper:/app
      - /app/node_modules
    depends_on:
      - web

  scraper-movies:
    build: ./scraper
    command: npm run start:movies
    env_file:
      - .env # Pasa la clave TMDB_API_KEY
    volumes:
      - ./scraper:/app
      - /app/node_modules
    depends_on:
      - web

  scraper-music:
    build: ./scraper
    command: npm run start:music
    volumes:
      - ./scraper:/app
      - /app/node_modules
    depends_on:
      - web

# volumen persistente para que los datos sobrevivan a reinicios
volumes:
  postgres_data:
    external: true
    name: library_manager_postgres_data