# Generated by Django 6.0.3 on 2026-04-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0002_adventurer_ardite_adventurer_copper_penny_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurer',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / Misterioso')], default='O', max_length=1),
        ),
    ]
