# Generated by Django 6.0.3 on 2026-04-14 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0003_adventurer_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('WPN', 'Arma'), ('AMR', 'Armadura'), ('ACC', 'Accesorio'), ('CNS', 'Consumible')], max_length=3)),
                ('rarity', models.CharField(choices=[('COM', 'Común'), ('UNC', 'Poco Común'), ('RAR', 'Raro'), ('EPC', 'Épico'), ('LEG', 'Legendario')], default='COM', max_length=3)),
                ('cost_in_copper', models.PositiveIntegerField(default=10)),
                ('stat_modifier', models.FloatField(default=0.0, help_text='Modificador matemático para el Oráculo')),
            ],
        ),
        migrations.AddField(
            model_name='adventurer',
            name='equipped_accessory',
            field=models.ForeignKey(blank=True, help_text='Aumenta la ganancia de experiencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carried_by', to='posada.item'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='equipped_armor',
            field=models.ForeignKey(blank=True, help_text='Reduce el riesgo de emboscadas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worn_by', to='posada.item'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='equipped_weapon',
            field=models.ForeignKey(blank=True, help_text='Aumenta el botín encontrado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wielded_by', to='posada.item'),
        ),
    ]
