# Generated by Django 6.0.3 on 2026-04-14 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0004_item_adventurer_equipped_accessory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventurer',
            name='equipped_accessory',
        ),
        migrations.RemoveField(
            model_name='adventurer',
            name='equipped_armor',
        ),
        migrations.RemoveField(
            model_name='adventurer',
            name='equipped_weapon',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stat_modifier',
        ),
        migrations.AddField(
            model_name='adventurer',
            name='base_cha',
            field=models.PositiveIntegerField(default=1, verbose_name='Carisma'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='base_con',
            field=models.PositiveIntegerField(default=1, verbose_name='Constitución'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='base_dex',
            field=models.PositiveIntegerField(default=1, verbose_name='Destreza'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='base_int',
            field=models.PositiveIntegerField(default=1, verbose_name='Inteligencia'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='base_luk',
            field=models.PositiveIntegerField(default=1, verbose_name='Suerte'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='base_str',
            field=models.PositiveIntegerField(default=1, verbose_name='Fuerza'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='base_wis',
            field=models.PositiveIntegerField(default=1, verbose_name='Sabiduría'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='current_hp',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='equip_accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_accessory', to='posada.item'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='equip_feet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_feet', to='posada.item'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='equip_hands',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_hands', to='posada.item'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='equip_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_head', to='posada.item'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='equip_legs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_legs', to='posada.item'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='equip_main_hand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_main', to='posada.item'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='equip_off_hand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_off', to='posada.item'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='equip_torso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_torso', to='posada.item'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='max_hp',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_armor',
            field=models.PositiveIntegerField(default=0, help_text='Suma a la Armadura (Ropa/Escudos)'),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_cha',
            field=models.IntegerField(default=0, verbose_name='Carisma'),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_con',
            field=models.IntegerField(default=0, verbose_name='Constitución'),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_damage',
            field=models.PositiveIntegerField(default=0, help_text='Suma al Daño (Armas)'),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_dex',
            field=models.IntegerField(default=0, verbose_name='Destreza'),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_int',
            field=models.IntegerField(default=0, verbose_name='Inteligencia'),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_luk',
            field=models.IntegerField(default=0, verbose_name='Suerte'),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_str',
            field=models.IntegerField(default=0, verbose_name='Fuerza'),
        ),
        migrations.AddField(
            model_name='item',
            name='bonus_wis',
            field=models.IntegerField(default=0, verbose_name='Sabiduría'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('W1H', 'Arma (1 Mano)'), ('W2H', 'Arma (2 Manos)'), ('OFF', 'Secundaria / Escudo'), ('HED', 'Cabeza'), ('TRS', 'Torso'), ('LGS', 'Piernas'), ('HND', 'Manos'), ('FET', 'Pies'), ('ACC', 'Accesorio'), ('CNS', 'Consumible')], max_length=3),
        ),
    ]
