# Generated by Django 6.0.3 on 2026-04-15 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0005_remove_adventurer_equipped_accessory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('S', 'Rango S (Épico - Mucha XP)'), ('A', 'Rango A (Difícil)'), ('B', 'Rango B (Medio)'), ('C', 'Rango C (Fácil - Poca XP)')], default='C', max_length=1)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('deep_work_minutes', models.PositiveIntegerField(default=0)),
                ('screen_time_minutes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='adventurer',
            name='fatigue_stacks',
            field=models.PositiveIntegerField(default=0, help_text='Cada stack resta -1 a todos los stats.'),
        ),
    ]
