# Generated by Django 6.0.3 on 2026-04-15 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0006_dailyhabit_dailystatistic_adventurer_fatigue_stacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventurer',
            name='equip_accessory',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cost_in_copper',
        ),
        migrations.AddField(
            model_name='adventurer',
            name='equip_bracelet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_bracelet', to='posada.item'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='equip_earring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_earring', to='posada.item'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='equip_necklace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_necklace', to='posada.item'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='equip_ring_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_ring_1', to='posada.item'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='equip_ring_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_ring_2', to='posada.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_ardite',
            field=models.PositiveIntegerField(default=0, verbose_name='Coste: Ardite'),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_copper_penny',
            field=models.PositiveIntegerField(default=0, verbose_name='Coste: Penique de cobre'),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_drabin',
            field=models.PositiveIntegerField(default=0, verbose_name='Coste: Drabín'),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_iota',
            field=models.PositiveIntegerField(default=0, verbose_name='Coste: Iota'),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_iron_half_penny',
            field=models.PositiveIntegerField(default=0, verbose_name='Coste: Medio penique de hierro'),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_iron_penny',
            field=models.PositiveIntegerField(default=0, verbose_name='Coste: Penique de hierro'),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_marco',
            field=models.PositiveIntegerField(default=0, verbose_name='Coste: Marco'),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_real',
            field=models.PositiveIntegerField(default=0, verbose_name='Coste: Real'),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_silver_penny',
            field=models.PositiveIntegerField(default=0, verbose_name='Coste: Penique de plata'),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_sueldo',
            field=models.PositiveIntegerField(default=0, verbose_name='Coste: Sueldo'),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_talento',
            field=models.PositiveIntegerField(default=0, verbose_name='Coste: Talento'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('W1H', 'Arma (1 Mano)'), ('W2H', 'Arma (2 Manos)'), ('OFF', 'Secundaria / Escudo'), ('HED', 'Cabeza'), ('TRS', 'Torso'), ('LGS', 'Piernas'), ('HND', 'Manos'), ('FET', 'Pies'), ('NCK', 'Collar'), ('RNG', 'Anillo'), ('BRC', 'Brazalete'), ('EAR', 'Aretes'), ('CNS', 'Consumible'), ('MSC', 'Misceláneo')], max_length=3),
        ),
        migrations.CreateModel(
            name='InventorySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('adventurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='posada.adventurer')),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_inventory', to='posada.guildprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posada.item')),
            ],
        ),
    ]
