# Generated by Django 6.0.3 on 2026-04-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0007_remove_adventurer_equip_accessory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='allowed_classes',
            field=models.JSONField(blank=True, default=list, help_text='Lista de códigos (WIZ, BBN, etc.) que pueden usar este item.'),
        ),
    ]
