# Generated by Django 6.0.3 on 2026-04-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0010_remove_monster_base_damage_item_damage_dice_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='max_spawn',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monster',
            name='min_spawn',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
