# Generated by Django 6.0.3 on 2026-05-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0012_customchart_dailyhabit_current_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customchart',
            name='x_min',
            field=models.FloatField(default=1.0, help_text='Inicio del Eje X (Ej: Día 1)'),
        ),
        migrations.AddField(
            model_name='customchart',
            name='y_max',
            field=models.FloatField(default=10.0, help_text='Techo del Eje Y (Ej: 6 horas máximo)'),
        ),
        migrations.AddField(
            model_name='customchart',
            name='y_min',
            field=models.FloatField(default=0.0, help_text='Suelo del Eje Y (Ej: 0 horas)'),
        ),
        migrations.AlterField(
            model_name='customchart',
            name='goal_x_value',
            field=models.PositiveIntegerField(default=30, help_text='Fin del Eje X / Meta (Ej: Día 30)'),
        ),
    ]
