# Generated by Django 6.0.3 on 2026-05-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0013_customchart_x_min_customchart_y_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyhabit',
            old_name='last_xp_reward',
            new_name='last_prestige_reward',
        ),
        migrations.RenameField(
            model_name='guildprofile',
            old_name='level',
            new_name='prestige_level',
        ),
        migrations.RemoveField(
            model_name='adventurer',
            name='fatigue_stacks',
        ),
        migrations.RemoveField(
            model_name='guildprofile',
            name='experience',
        ),
        migrations.AddField(
            model_name='guildprofile',
            name='prestige',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyhabit',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyhabit',
            name='valid_days',
            field=models.CharField(default='0,1,2,3,4,5,6', max_length=20),
        ),
    ]
