# Generated by Django 6.0.3 on 2026-05-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0014_rename_last_xp_reward_dailyhabit_last_prestige_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurer',
            name='inventory_capacity',
            field=models.PositiveIntegerField(default=10, help_text='Máximo de slots en la mochila'),
        ),
    ]
