# Generated by Django 6.0.3 on 2026-05-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0015_adventurer_inventory_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyhabit',
            name='is_bad_habit',
            field=models.BooleanField(default=False, help_text='Si es True, marcarlo es una recaída (castigo).'),
        ),
        migrations.AddField(
            model_name='dailyhabit',
            name='previous_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
