# Generated by Django 6.0.3 on 2026-05-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posada', '0017_journalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuildUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='ID interno (ej: mensajeria_arcana)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost_coin', models.CharField(default='talento', help_text='Moneda requerida', max_length=20)),
                ('cost_amount', models.PositiveIntegerField(default=1)),
                ('req_prestige_level', models.PositiveIntegerField(default=1, help_text='Nivel de Gremio requerido')),
            ],
        ),
        migrations.RemoveField(
            model_name='adventurer',
            name='inventory_capacity',
        ),
        migrations.CreateModel(
            name='GuildUnlockedUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_upgrades', to='posada.guildprofile')),
                ('upgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posada.guildupgrade')),
            ],
            options={
                'unique_together': {('guild', 'upgrade')},
            },
        ),
    ]
