API_LIBRARY = "http://localhost:8000/api/books/library/"
API_SCAN = "http://localhost:8000/api/books/scan/"
API_INBOX = "http://localhost:8000/api/books/inbox/"
API_LOANS = "http://localhost:8000/api/books/loans/"
API_TRACKER = "http://localhost:8000/api/books/tracker/stats/"
API_WISHLIST = "http://localhost:8000/api/books/wishlist-crud/"
API_DIRECTORIES = "http://localhost:8000/api/books/directories/"
API_TRACKER_ANNUAL = "http://localhost:8000/api/books/tracker/annual/"
API_FRIENDS = "http://localhost:8000/api/books/friends/"
API_TRACKER_PAGES = "http://localhost:8000/api/books/tracker/pages/"
API_TRACKER_FINISH = "http://localhost:8000/api/books/tracker/finish/"
API_WATCHERS = "http://localhost:8000/api/books/watchers-crud/"
API_LOG_PAGES = "http://localhost:8000/api/books/log-pages/"
# --- RUTAS DEL VIDEOCLUB (MOVIE SHELL) ---
API_MOVIES = "http://localhost:8000/api/movies/inventory/"
API_MOVIE_DIRS = "http://localhost:8000/api/movies/directories/"
API_MOVIE_INBOX = "http://localhost:8000/api/movies/inbox/"
API_MOVIE_PROCESS = "http://localhost:8000/api/movies/process-barcode/"
API_MOVIE_SCAN = "http://localhost:8000/api/movies/scan/"
API_MOVIE_WATCHERS = "http://localhost:8000/api/movies/watchers/"
API_MOVIE_WISHLIST = "http://localhost:8000/api/movies/wishlist/"
# API para el tracker de películas
API_MOVIE_TRACKER = "http://localhost:8000/api/movies/tracker/stats/"
API_MOVIE_TRACKER_ANNUAL = "http://localhost:8000/api/movies/tracker/annual/"
API_MOVIE_TRACKER_MINUTES = "http://localhost:8000/api/movies/tracker/minutes/"
API_MOVIE_TRACKER_FINISH = "http://localhost:8000/api/movies/tracker/finish/"

API_DASHBOARD = "http://localhost:8000/api/dashboard/"
