# Generated by Django 6.0.3 on 2026-03-16 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Science Fiction, Fantasy, Cyberpunk', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('format_type', models.CharField(choices=[('NOVEL', 'Novel'), ('COMIC', 'Comic Book'), ('MANGA', 'Manga'), ('ANTHOLOGY', 'Anthology')], default='NOVEL', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, help_text='Rating from 1 to 5', null=True)),
                ('volume_number', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author')),
                ('genres', models.ManyToManyField(help_text='Select genres for this book', to='catalog.genre')),
            ],
        ),
    ]
