# Generated by Django 6.0.3 on 2026-03-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='book',
            name='volume_number',
        ),
        migrations.AddField(
            model_name='book',
            name='is_series',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='owned_volumes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='total_volumes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='catalog.genre'),
        ),
    ]
