# Generated by Django 6.0.3 on 2026-03-16 23:41

import catalog.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_friend_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='is_returned',
            new_name='returned',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='borrow_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='expected_return_date',
        ),
        migrations.AddField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=catalog.models.default_due_date),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book'),
        ),
    ]
