# Generated by Django 6.0.3 on 2026-03-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='format_type',
            field=models.CharField(choices=[('NOVEL', 'Novela'), ('MANGA', 'Manga / Cómic'), ('COMIC', 'Cómic Occidental'), ('ANTHOLOGY', 'Antología / Cuentos'), ('ACADEMIC', 'Libro Académico')], default='NOVEL', max_length=20),
        ),
    ]
