# Generated by Django 6.0.3 on 2026-03-23 14:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_book_format_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pages_read', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnnualRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_owned', models.BooleanField(default=True)),
                ('date_finished', models.DateField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_records', to='catalog.book')),
            ],
        ),
    ]
