# Generated by Django 6.0.3 on 2026-04-28 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_scaninbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualrecord',
            name='date_finished',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
