# Generated by Django 6.0.3 on 2026-04-01 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_hex', models.CharField(default='blue', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.CharField(default='Desconocido', max_length=255)),
                ('cast', models.TextField(blank=True, help_text='Reparto principal, separado por comas')),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('format_type', models.CharField(choices=[('DVD', 'DVD'), ('BLU-RAY', 'Blu-ray'), ('4K', '4K UHD'), ('VHS', 'VHS'), ('DIGITAL', 'Digital')], default='BLU-RAY', max_length=20)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('synopsis', models.TextField(blank=True)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('is_watched', models.BooleanField(default=False)),
                ('is_loaned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movies.moviedirectory')),
            ],
        ),
    ]
