# Generated by Django 6.0.3 on 2026-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviewatcher_moviewishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=255, unique=True)),
                ('date_scanned', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
