# Generated by Django 6.0.3 on 2026-04-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movieinbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinbox',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
