# Generated by Django 6.0.3 on 2026-04-08 10:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_friend_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieViewingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('minutes_watched', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieAnnualRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('is_owned', models.BooleanField(default=True)),
                ('date_watched', models.DateField(default=django.utils.timezone.localdate)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_records', to='movies.movie')),
            ],
        ),
    ]
