# Generated by Django 6.0.3 on 2026-04-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movieviewingsession_movieannualrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='production_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='writers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
